version: '3.7'

services:
  nats:
    image: nats:2.10.5
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    volumes:
      - ./nats-server.conf:/etc/nats/nats-server.conf
    command: "-c /etc/nats/nats-server.conf"