{
 "title": "Image Processing Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "language", "query": "scala,cpp,go,julia,elixir" },
   { "name": "window", "query": "1min,2min,5min,10min" },
   { "name": "stage", "query": "format ,resolution,size" }
  ]
 },
 "panels": [
  { "title": "$stage worker metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "stage" },
  {
   "title": "Per node throughput - $stage worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.$stage.*.results_produced, 2, 'sum'), 'avg'), '$window'), 'mean')"
    },
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.$stage.*.results_produced, 2, 'sum'), 'max'), '$window'), 'max')"
    },
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.$stage.*.results_produced, 2, 'sum'), 'min'), '$window'), 'min')"
    }
   ]
  },
  {
   "title": "Measured Workers - $stage worker",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(groupByNodes(stats.gauges.cadvisor.ip_${language}_${stage}_worker.*.*.memory_usage, 'count'), '${stage}_worker')"
    }
   ]
  },
  {
   "title": "Combined throughput - $stage worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "target": "aggregate(groupByNode(stats.$stage.*.results_produced, 2, 'sum'), 'sum')"
    }
   ]
  },
  {
   "title": "Coefficient of variation - $stage worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" },
    { "expression": "$D/$E", "type": "math" }
   ]
  },
  {
   "title": "Memory Usage - $stage worker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.gauges.cadvisor.ip_${language}_${stage}_worker.*.*.memory_usage, 4, 'sum'), 'avg'), '$window'), 'mean')"
    },
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.gauges.cadvisor.ip_${language}_${stage}_worker.*.*.memory_usage, 4, 'sum'), 'max'), '$window'), 'max')"
    },
    {
     "target": "alias(movingAverage(aggregate(groupByNode(stats.gauges.cadvisor.ip_${language}_${stage}_worker.*.*.memory_usage, 4, 'sum'), 'min'), '$window'), 'min')"
    }
   ]
  },
  {
   "title": "CPU usage - $stage worker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Network usage - $stage worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "target": "alias(aggregate(groupByNode(stats.gauges.cadvisor.ip_${language}_${stage}_worker.*.*.rx_bytes, 4, 'sum'), 'avg'), 'received')"
    },
    {
     "target": "alias(aggregate(groupByNode(stats.gauges.cadvisor.ip_${language}_${stage}_worker.*.*.tx_bytes, 4, 'sum'), 'avg'), 'transmitted')"
    }
   ]
  },
  { "title": "Aggregated metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Combined throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 48 },
   "targets": [
    {
     "target": "alias(aggregate(groupByNode(stats.size.*.results_produced, 2, 'sum'), 'sum'), 'size_worker')"
    },
    {
     "target": "alias(aggregate(groupByNode(stats.resolution.*.results_produced, 2, 'sum'), 'sum'), 'resolution_worker')"
    },
    {
     "target": "alias(aggregate(groupByNode(stats.format.*.results_produced, 2, 'sum'), 'sum'), 'format_worker')"
    }
   ]
  },
  {
   "title": "Completion Time - Manager",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.manager.completion_time"
    }
   ]
  },
  {
   "title": "Coefficient of variation - Work time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" },
    { "expression": "$G/$H", "type": "math" },
    { "expression": "$J/$K", "type": "math" }
   ]
  },
  {
   "title": "Coefficient of variation - Results produced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$B/$A", "type": "math" },
    { "expression": "$E/$D", "type": "math" },
    { "expression": "$H/$G", "type": "math" }
   ]
  },
  {
   "title": "Memory Usage - $window window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(movingWindow(aggregate(groupByNode(stats.gauges.cadvisor.ip_${language}_size_worker.*.*.memory_usage, 4, 'sum'), 'avg'), '$window', 'average'), 'size_worker')"
    },
    {
     "target": "alias(movingWindow(aggregate(groupByNode(stats.gauges.cadvisor.ip_${language}_format_worker.*.*.memory_usage, 4, 'sum'), 'avg'), '$window', 'average'), 'resolution_worker')"
    },
    {
     "target": "alias(movingWindow(aggregate(groupByNode(stats.gauges.cadvisor.ip_${language}_resolution_worker.*.*.memory_usage, 4, 'sum'), 'avg'), '$window', 'average'), 'format_worker')"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" },
    { "expression": "$D/$E", "type": "math" },
    { "expression": "$G/$H", "type": "math" }
   ]
  },
  {
   "title": "Network - received bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "target": "alias(aggregate(groupByNode(stats.gauges.cadvisor.ip_${language}_size_worker.*.*.rx_bytes, 4, 'sum'), 'avg'), 'size_worker')"
    },
    {
     "target": "alias(aggregate(groupByNode(stats.gauges.cadvisor.ip_${language}_resolution_worker.*.*.rx_bytes, 4, 'sum'), 'avg'), 'resolution_worker')"
    },
    {
     "target": "alias(aggregate(groupByNode(stats.gauges.cadvisor.ip_${language}_format_worker.*.*.rx_bytes, 4, 'sum'), 'avg'), 'format_worker')"
    }
   ]
  },
  {
   "title": "Network - transmitted bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "target": "alias(aggregate(groupByNode(stats.gauges.cadvisor.ip_${language}_size_worker.*.*.tx_bytes, 4, 'sum'), 'avg'), 'size_worker')"
    },
    {
     "target": "alias(aggregate(groupByNode(stats.gauges.cadvisor.ip_${language}_resolution_worker.*.*.tx_bytes, 4, 'sum'), 'avg'), 'resolution_worker')"
    },
    {
     "target": "alias(aggregate(groupByNode(stats.gauges.cadvisor.ip_${language}_format_worker.*.*.tx_bytes, 4, 'sum'), 'avg'), 'format_worker')"
    }
   ]
  }
 ]
}